# -*- coding: utf-8 -*-
"""Generated imgs from articles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ONNyJJOozyTkBt_Hj7kSsgJVrn50D2i
"""

!pip install diffusers transformers accelerate safetensors

import torch
import os
from diffusers import StableDiffusionPipeline

device = "cuda" if torch.cuda.is_available() else "cpu"
os.makedirs("Article 1", exist_ok=True)

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5").to(device)

# Image 1
prompt1 = "photorealistic aerial image of a massive solar farm in a desert, endless rows of blue solar panels, heat haze, bright sunlight, extremely detailed 4k"
image1 = pipe(prompt1).images[0]
image1.save("Article 1/solar_farm_desert.png")

# Image 2
prompt2 = "realistic 4k image of a wind-powered classroom in Morocco, students studying inside a bright classroom, large wind turbines visible outside, emotional and inspiring atmosphere, highly detailed"
image2 = pipe(prompt2).images[0]
image2.save("Article 1/wind_powered_classroom_morocco.png")

print("Done - 2 images saved")

import torch
import os
from diffusers import StableDiffusionPipeline

device = "cuda" if torch.cuda.is_available() else "cpu"
os.makedirs("Article2_Outputs", exist_ok=True)

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5").to(device)

# Image 1: Digital activism
prompt1 = "realistic photo of Gen Z youth protest in Nairobi Kenya, young activists with smartphones, emotional determined faces, crowded streets, protest signs, dramatic lighting, 4k"
image1 = pipe(prompt1).images[0]
image1.save("Article2_Outputs/youth_protest_kenya.png")

# Image 2: Nepal protest victory
prompt2 = "realistic image of youth celebration in Nepal after government change, emotional joyful faces, victory signs, crowded streets, political change, powerful moment, 4k"
image2 = pipe(prompt2).images[0]
image2.save("Article2_Outputs/nepal_youth_victory.png")

print("Article 2 - 2 new images saved")

import torch
import os
from diffusers import StableDiffusionPipeline

device = "cuda" if torch.cuda.is_available() else "cpu"
os.makedirs("Article3_Outputs", exist_ok=True)

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5").to(device)

# Image 1: AI image generation
prompt1 = "photorealistic image of a person using AI to generate stunning digital art on computer, futuristic interface, creative technology, detailed 4k"
image1 = pipe(prompt1).images[0]
image1.save("Article3_Outputs/ai_art_generation.png")

# Image 2: AI impact on society
prompt2 = "realistic photo showing human-AI collaboration, diverse people working with AI assistants, modern office, technology integration, emotional connection, 4k"
image2 = pipe(prompt2).images[0]
image2.save("Article3_Outputs/human_ai_collaboration.png")

print("Article 3 - 2 images saved")